permalink: pretty
exclude: ['Makefile', 'README.md', '_ignore', '_less']

domain: homenetworks.ac.uk
title: Homework &ndash; user-centred home networking
author: Richard Mortier
email: richard.mortier@nottingham.ac.uk

google_analytics:
  account: UA-35397059-1
