# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Makefile', 'README.md', '_ignore']
markdown: maruku

# configuration required for some pages

domain: blog.example.com
title: My Blog Title
author: Me
email: me@example.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-35397059-1

# github:
#   username: ghusername

# disqus:
#   id: disqusid
